name: three_x_plus_1
description: A simple set of widgets to demonstrate the mathmatical 3x + 1 conjecture.
homepage: https://github.com/peiffer-innovations/three_x_plus_1

version: 1.0.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  charts_flutter: ^0.11.0
  flutter:
    sdk: flutter
  provider: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
